# Generated by Django 3.2.4 on 2024-11-27 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_posts',
            field=models.ManyToManyField(related_name='post_share', through='shares.Share', to=settings.AUTH_USER_MODEL),
        ),
    ]
